# -*- coding: utf- 8 -*-
import random 
print (u"Программа писькомер. Позволит вам узнать размер вашей колбаски.")
print (u"Ваш кран вырос до") 
print(random.randint(1,25)) 
print (u"см")

print (u"Автор сия творения Владислав Пастерпанк")


